### ISSUE TITLE
Write a proof that single linkage is in fact the same algorithm

### ISSUE THREAD

**Issue by RokIvansek** [ptrus/vietoris_rips_image_classification#1]

**Comment by RokIvansek** [comment]
I added the proof to our report. Please read it and comment as I am insecure about a specific part in it. The part is labeled so you should know it when you read it. :)

**Comment by adolenc** [comment]
After a very quick check this looks pretty good as is. The only two minor problems I found are:
- the use of capital V to denote both Vietoris-Rips complex and the vertices of a graph -- using VR_r for Vietoris-Rips cx, as we've done at lectures would probably make it a tad more readable; and
- I am also not completely sure whether we should use the definition of V-R cx from the lectures: ![render](https://cloud.githubusercontent.com/assets/9569399/15017957/018b20a0-1218-11e6-9bde-69808e892b19.jpg) (in which case d_{max} should have a factor of 2 (or maybe 1/2) somewhere), or just leave the definition as it is right now.

But then at the same time, looking through a bunch of literature it would seem that different authors use different conventions for both of these points, so the only reason to change them would be so that we are consistent with the lecture notes, which might not really be worth the time thinking about it.

Other than this I have some minor trouble understanding the proof, but I think it would be easier (and quicker) to clear my misunderstandings if we met in person.

Very good job though :+1: !

**Comment by RokIvansek** [comment]
Thx for the feedback. :)

By thinking about it some more I came up with the idea for the proof via induction. It seems a lot more intuitive and clear to me. Also:
-removed the old proof,
-fixed the notation which was indeed confusing,
-changed the definition of connected components,
-left the definition of VR as it is (if you both think we should change it let me know and I will).

Please let me know if you have any issues with the proof.
